-- leverage X V63 — canonical launch-event mirror for external launchpad indexers.
-- Run after v55_production_launch.sql.

create table if not exists public.leveragex_v63_chain_events (
  id bigint generated by default as identity primary key,
  chain_id bigint not null check (chain_id = 4663),
  factory_address text not null check (factory_address ~ '^0x[0-9a-f]{40}$'),
  block_number bigint not null,
  block_hash text not null check (block_hash ~ '^0x[0-9a-f]{64}$'),
  transaction_hash text not null check (transaction_hash ~ '^0x[0-9a-f]{64}$'),
  transaction_index integer not null check (transaction_index >= 0),
  log_index integer not null check (log_index >= 0),
  event_name text not null check (event_name in ('TokenLaunched','MarketCreated','Trade','TokenGraduated','Transfer')),
  token_address text,
  market_address text,
  creator_address text,
  payload jsonb not null default '{}'::jsonb,
  canonical boolean not null default true,
  observed_at timestamptz not null default now(),
  unique (chain_id, transaction_hash, log_index)
);

create index if not exists leveragex_v63_events_block_idx
  on public.leveragex_v63_chain_events (chain_id, block_number, transaction_index, log_index);
create index if not exists leveragex_v63_events_token_idx
  on public.leveragex_v63_chain_events (token_address, block_number desc) where canonical;
create index if not exists leveragex_v63_events_factory_idx
  on public.leveragex_v63_chain_events (factory_address, block_number desc) where canonical;

alter table public.leveragex_v63_chain_events enable row level security;
drop policy if exists "Public can read canonical V63 chain events" on public.leveragex_v63_chain_events;
create policy "Public can read canonical V63 chain events"
  on public.leveragex_v63_chain_events for select
  using (canonical = true);

create table if not exists public.leveragex_v63_indexer_checkpoints (
  chain_id bigint not null check (chain_id = 4663),
  factory_address text not null check (factory_address ~ '^0x[0-9a-f]{40}$'),
  last_finalized_block bigint not null default 0,
  last_finalized_hash text,
  updated_at timestamptz not null default now(),
  primary key (chain_id, factory_address)
);

alter table public.leveragex_v63_indexer_checkpoints enable row level security;
-- No public write/read policy: service-role only.

comment on table public.leveragex_v63_chain_events is
  'Raw, ordered, reorg-aware Leverage X launch/trade events for GMGN and other indexer integrations.';
