import { existsSync,readFileSync } from "node:fs";
let passed=0;const file=(p:string)=>readFileSync(p,"utf8");const check=(label:string,ok:boolean)=>{if(!ok)throw new Error(`V65 smoke failed: ${label}`);passed++;console.log(`✓ ${label}`)};
const contract=file("contracts/src/LeverageXLaunchFactoryV65.sol"),test=file("contracts/test/LeverageXLaunchFactoryV65.t.sol"),client=file("lib/chain/robinhood-v65.ts"),manifest=file("lib/server/v65-gmgn-live.ts"),launchServer=file("lib/server/v65-launch-server.ts"),panel=file("components/LaunchPanel.tsx"),market=file("components/MarketProvider.tsx"),backfill=file("scripts/v65-gmgn-live-backfill.mts"),deploy=file("scripts/v65-deploy-mainnet.mts"),schema=file("supabase/v65_gmgn_live_pool.sql"),pkg=file("package.json");
check("V65 canonical launch contract packaged",contract.includes("contract LeverageXLaunchFactoryV65"));
check("tax-free fixed 1B ERC20",contract.includes("totalSupply = 1_000_000_000 ether")&&!contract.includes("transferTax"));
check("official Robinhood WETH configured",contract.toLowerCase().includes("0x0bd7d308f8e1639fab988df18a8011f41eacad73"));
check("official Uniswap V3 factory configured",contract.toLowerCase().includes("0x1f7d7550b1b028f7571e69a784071f0205fd2efa"));
check("official position manager configured",contract.toLowerCase().includes("0x73991a25c818bf1f1128deaab1492d45638de0d3"));
check("official SwapRouter02 configured",contract.toLowerCase().includes("0xcaf681a66d020601342297493863e78c959e5cb2"));
check("official QuoterV2 published",contract.toLowerCase().includes("0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7"));
check("canonical pool exists in launch transaction",contract.includes("createAndInitializePoolIfNecessary")&&contract.includes("CanonicalPoolCreated"));
check("token address uses dynamic CREATE2 anti-squatting salt",contract.includes("block.prevrandao")&&contract.includes("new LeverageXTokenV65{salt: launchSalt}"));
check("creator initial buy routes through standard router",contract.includes("swapRouter.exactInputSingle{value: msg.value}"));
check("launch LP NFT is permanently locked",contract.includes("recipient: address(liquidityLocker)")&&contract.includes("LaunchPositionLocked"));
check("graduation stays in same canonical pool",contract.includes("function graduateToken")&&contract.includes("FinalLiquidityLocked"));
check("graduation resists one-block tick manipulation",contract.includes("GRADUATION_TWAP_SECONDS")&&contract.includes("pool.observe(secondsAgos)")&&test.includes("testCannotGraduateFromOneBlockTerminalTickManipulation"));
check("locker validates factory pool mapping",contract.includes("dexFactory.getPool(token0, token1, poolFee) != pool"));
check("factory remains closed by default",contract.includes("launchMode = LaunchMode.Closed")&&contract.includes("launchCreationPaused = true"));
check("users cannot choose protocol migration target",!panel.includes("migration target")&&!panel.includes("migrationTarget"));
check("launch UI uses V65 metadata and registry",panel.includes("/api/v65/metadata")&&panel.includes("/api/v65/launches"));
check("browser client supports V65 launch buy sell",client.includes("launchV65Token")&&client.includes("executeV65SpotBuy")&&client.includes("executeV65SpotSell"));
check("browser trades quote through QuoterV2",client.includes("quoteExactInput")&&client.includes("V65_QUOTER_V2"));
check("terminal routes V65 trades through Uniswap",market.includes("isV65SpotMarket")&&market.includes("executeV65SpotBuy")&&market.includes("executeV65SpotSell"));
check("server verifies canonical pool mapping",launchServer.includes("canonicalPoolForToken")&&launchServer.includes("TokenLaunched"));
check("public V65 manifest publishes standard pool events",manifest.includes("V65_POOL_EVENTS")&&manifest.includes("poolFromFirstBlock: true"));
check("public V65 GMGN APIs packaged",existsSync("app/api/v65/gmgn/manifest/route.ts")&&existsSync("app/api/v65/gmgn/token/[address]/route.ts")&&existsSync("app/api/v65/gmgn/pool-events/route.ts"));
check("public V65 ABIs packaged",["LeverageXLaunchFactoryV65.json","LeverageXTokenV65.json","LeverageXPermanentLiquidityLockerV65.json","LeverageXCanonicalPoolV65.json"].every(f=>existsSync(`public/integrations/gmgn/abi/${f}`)));
check("reorg-aware factory and pool backfill packaged",backfill.includes("eth_getLogs")&&backfill.includes("canonical:false")&&backfill.includes("leveragex_v65_pool_events"));
check("Supabase mirrors standard Swap events",schema.includes("leveragex_v65_pool_events")&&schema.includes("'Swap'")&&schema.includes("block_hash"));
check("closed deployment binds immutable locker",deploy.includes("bindFactory(address)")&&deploy.includes("launchCreationPaused()(bool)"));
check("real roundtrip uses quote-derived slippage floors",file("scripts/v65-trader-roundtrip.mts").includes("minimumBuy")&&file("scripts/v65-trader-roundtrip.mts").includes("minimumSell"));
check("GMGN handoff package generator packaged",existsSync("scripts/v65-build-gmgn-package.mts")&&pkg.includes("gmgn:package:v65"));
check("read-only GMGN operator console packaged",existsSync("components/V65GmgnLiveConsole.tsx")&&existsSync("app/admin/gmgn-live/page.tsx"));
check("contract tests cover pool mapping and graduation",test.includes("testCanaryLaunchCreatesCanonicalPoolAndPermanentPosition")&&test.includes("testGraduationReplacesLaunchNftWithPermanentFullRangeNft"));
check("V65 commands wired",pkg.includes("chain:v65:preflight")&&pkg.includes("chain:v65:trader:roundtrip")&&pkg.includes("test:v65-fast"));
console.log(`\nV65 GMGN live-pool controls: ${passed}/${passed} checks passed.`);
