import { mkdirSync,writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DEFAULT_FIRST_TRADER,normalizeAddress,requireRpc,run,walletArgsFor } from "./v59-mainnet-common.mts";
import { V65_DEX } from "./v65-mainnet-common.mts";

const CONFIRM="RUN_V65_REAL_SPOT_ROUNDTRIP";
if(process.env.V65_TRADER_ROUNDTRIP_CONFIRM!==CONFIRM)throw new Error(`Locked. Set V65_TRADER_ROUNDTRIP_CONFIRM=${CONFIRM}.`);
const RPC=requireRpc(),token=normalizeAddress(process.env.V65_FIRST_TOKEN_ADDRESS,"V65_FIRST_TOKEN_ADDRESS"),pool=normalizeAddress(process.env.V65_FIRST_POOL_ADDRESS,"V65_FIRST_POOL_ADDRESS"),trader=normalizeAddress(process.env.V65_FIRST_TRADER_ADDRESS,"V65_FIRST_TRADER_ADDRESS",DEFAULT_FIRST_TRADER),wallet=walletArgsFor("V65_TRADER",trader);
const signer=run("cast",["wallet","address",...wallet.args],{redact:wallet.redactions}).toLowerCase();if(signer!==trader)throw new Error("Trader signer mismatch.");
const call=(to:string,sig:string,...args:string[])=>run("cast",["call",to,sig,...args,"--rpc-url",RPC],{redact:[RPC]});
const poolToken0=call(pool,"token0()(address)").toLowerCase(),poolToken1=call(pool,"token1()(address)").toLowerCase();if(!((poolToken0===token&&poolToken1===V65_DEX.wrappedNative)||(poolToken1===token&&poolToken0===V65_DEX.wrappedNative)))throw new Error("V65 pool/token mismatch.");
const quote=(tokenIn:string,tokenOut:string,amountIn:bigint)=>{const raw=call(V65_DEX.quoterV2,"quoteExactInputSingle((address,address,uint256,uint24,uint160))((uint256,uint160,uint32,uint256))",`(${tokenIn},${tokenOut},${amountIn},${V65_DEX.fee},0)`);const first=raw.match(/(?:^|\()\s*(0x[0-9a-fA-F]+|\d+)/)?.[1];if(!first)throw new Error(`Unable to parse QuoterV2 output: ${raw}`);return BigInt(first);};
const balance=()=>BigInt(call(token,"balanceOf(address)(uint256)",trader));
const buyWei=BigInt(process.env.V65_TRADER_BUY_WEI??"100000000000000");const quotedBuy=quote(V65_DEX.wrappedNative,token,buyWei);const minimumBuy=quotedBuy*98n/100n;const before=balance();const buyTuple=`(${V65_DEX.wrappedNative},${token},${V65_DEX.fee},${trader},${buyWei},${minimumBuy},0)`;const buy=JSON.parse(run("cast",["send",V65_DEX.swapRouter02,"exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))",buyTuple,"--value",buyWei.toString(),"--rpc-url",RPC,...wallet.args,"--json"],{redact:[RPC,...wallet.redactions]})) as any;const after=balance();const received=after-before;if(received<=0n)throw new Error("Trader buy produced no tokens.");
const sellBps=Math.max(1,Math.min(10_000,Number(process.env.V65_TRADER_SELL_BPS??5000)));const sell=received*BigInt(sellBps)/10_000n;if(sell<=0n)throw new Error("Sell amount rounded to zero.");const quotedSell=quote(token,V65_DEX.wrappedNative,sell);const minimumSell=quotedSell*98n/100n;const approval=JSON.parse(run("cast",["send",token,"approve(address,uint256)",V65_DEX.swapRouter02,sell.toString(),"--rpc-url",RPC,...wallet.args,"--json"],{redact:[RPC,...wallet.redactions]})) as any;const sellTuple=`(${token},${V65_DEX.wrappedNative},${V65_DEX.fee},${trader},${sell},${minimumSell},0)`;const wethBefore=BigInt(call(V65_DEX.wrappedNative,"balanceOf(address)(uint256)",trader));const swap=JSON.parse(run("cast",["send",V65_DEX.swapRouter02,"exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))",sellTuple,"--rpc-url",RPC,...wallet.args,"--json"],{redact:[RPC,...wallet.redactions]})) as any;const wethAfter=BigInt(call(V65_DEX.wrappedNative,"balanceOf(address)(uint256)",trader));const weth=wethAfter-wethBefore;if(weth<=0n)throw new Error("Sell produced no WETH.");const unwrap=JSON.parse(run("cast",["send",V65_DEX.wrappedNative,"withdraw(uint256)",weth.toString(),"--rpc-url",RPC,...wallet.args,"--json"],{redact:[RPC,...wallet.redactions]})) as any;
const report={version:"V65",completedAt:new Date().toISOString(),token,pool,trader,buyWei:buyWei.toString(),quotedBuyTokens:quotedBuy.toString(),minimumBuyTokens:minimumBuy.toString(),buyTransactionHash:buy.transactionHash??null,tokensReceived:received.toString(),approvalTransactionHash:approval.transactionHash??null,sellBps,sellTokens:sell.toString(),quotedSellWeth:quotedSell.toString(),minimumSellWeth:minimumSell.toString(),sellTransactionHash:swap.transactionHash??null,wethUnwrappedWei:weth.toString(),unwrapTransactionHash:unwrap.transactionHash??null};mkdirSync(resolve("deployments"),{recursive:true});writeFileSync(resolve("deployments","v65-trader-roundtrip.json"),`${JSON.stringify(report,null,2)}\n`);console.log("V65 real Spot buy/sell/unwrap roundtrip completed. Evidence: deployments/v65-trader-roundtrip.json");
